import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "./components/LayoutWrapper"; // ⬅️ подключаем обёртку

// Используем шрифт Roboto
const roboto = Roboto({
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500"],
  variable: "--font-roboto",
});

// Метаданные для страницы
export const metadata: Metadata = {
  title: "LunguaNova",
  description: "Generated by create next app",
};

// Компонент Layout
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
